// Generated by JavaCPP version 1.5.3: DO NOT EDIT THIS FILE

#include <jni.h>
#include "../include/vkt2/vector.hpp"

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

#ifdef __cplusplus
}
#endif
