// Generated by JavaCPP version 1.5.3: DO NOT EDIT THIS FILE

#include <jni.h>
#include "./include/GLFW/glfw3.h"
#include "./include/vkt2/fw.hpp"
#include "./include/JiviX/JiviX.hpp"

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

#ifdef __cplusplus
}
#endif
