// Generated by JavaCPP version 1.5.2: DO NOT EDIT THIS FILE

#include <jni.h>
#include <algorithm>
#include "JiviX.h"

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback1(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback2(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback3(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback4(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback5(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback6(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback7(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback8(int arg0, int arg1);
JNIIMPORT int JavaCPP_FooJiviX_00024Callback_allocate_callback9(int arg0, int arg1);
JNIIMPORT int jvx_foo(int arg0, int arg1);
JNIIMPORT int jvx_foo1(int arg0, int arg1);
JNIIMPORT int jvx_foo2(int arg0, int arg1);
JNIIMPORT int jvx_foo3(int arg0, int arg1);
JNIIMPORT int jvx_foo4(int arg0, int arg1);
JNIIMPORT int jvx_foo5(int arg0, int arg1);
JNIIMPORT int jvx_foo6(int arg0, int arg1);
JNIIMPORT int jvx_foo7(int arg0, int arg1);
JNIIMPORT int jvx_foo8(int arg0, int arg1);
JNIIMPORT int jvx_foo9(int arg0, int arg1);
#ifdef __cplusplus
}
#endif
